services:

  app:
    build: .
    container_name: rag-chatbot
    ports:
      - "7860:7860"
    volumes:
      - chroma_data:/app/chroma_db   # Base vectorial persiste
      - ./docs:/app/docs             # Monta tus PDFs aquí
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL}

volumes:
  chroma_data: